CREATE DATABASE examendb;
USE examendb;
CREATE TABLE UnidadDidactica (
ID INTEGER PRIMARY KEY,
ACRONIMO VARCHAR(20),
TITULO VARCHAR(20),
EVALUACION VARCHAR(20),
DESCRIPCION VARCHAR(20)
);
CREATE TABLE ConvocatoriaExamen (
CONVOCATORIA VARCHAR(20) PRIMARY KEY,
DESCRIPCION VARCHAR(20),
FECHA DATE,
CURSO VARCHAR(20)
);
CREATE TABLE Eunciado (
ID INTEGER PRIMARY KEY,
DESCRIPCION VARCHAR(20),
NIVEL ENUM("ALTA","MEDIA","BAJA"),
DISPONIBLE BOOLEAN,
RUTA VARCHAR(20),
CONVOCATORIA VARCHAR(20),
FOREIGN KEY (CONVOCATORIA) REFERENCES ConvocatoriaExamen(CONVOCATORIA) ON DELETE CASCADE
);
CREATE TABLE EnunciadoUnidad (
ID_ENUNCIADO INTEGER,
ID_UNIDAD INTEGER,
PRIMARY KEY (ID_ENUNCIADO,ID_UNIDAD),
FOREIGN KEY (ID_UNIDAD) REFERENCES UnidadDidactica(ID) ON DELETE CASCADE,
FOREIGN KEY (ID_ENUNCIADO) REFERENCES Eunciado(ID) ON DELETE CASCADE
);